### Common

server:
  port: 33001

spring:
  application:
    name: Gateway
  profiles:
    active: dev

ribbon:
  eureka:
    enabled: true

zuul:
  sensitiveHeaders:

---

### Dev profile

spring:
  profiles: dev

eureka:
  client:
    enabled: false

logging:
  level:
    com.chumbok: DEBUG

---

### Prod profile

spring:
  profiles: prod

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:33000/eureka/

logging:
  level:
    com.chumbok: DEBUG

---

spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:33000/eureka/

---

### Enable Eureka profile

spring:
  profiles: eureka

eureka:
  client:
    enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:33000/eureka/
